version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
- package-ecosystem: npm
  directory: "/webapp"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
- package-ecosystem: docker
  directory: "/webapp"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
- package-ecosystem: docker
  directory: "/neo4j"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
- package-ecosystem: docker
  directory: "/deployment/legacy-migration/maintenance-worker"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  # open-pull-requests-limit: 10
  # ignore:
