version: "3.4"

services:
  webapp:
    image: schoolsinmotion/webapp:latest
    ports:
      - 3000:3000
      - 3002:3002
    networks:
      - hc-network
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - GRAPHQL_URI=http://backend:4000
      - MAPBOX_TOKEN="pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.bZ8KK9l70omjXbEkkbHGsQ"
      - PUBLIC_REGISTRATION=true
    command: yarn run dev
  backend:
    image: schoolsinmotion/backend:latest
    networks:
      - hc-network
    depends_on:
      - neo4j
    ports:
      - 4000:4000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - GRAPHQL_URI=http://backend:4000
      - CLIENT_URI=http://localhost:3000
      - JWT_SECRET=b/&&7b78BF&fv/Vd
      - MAPBOX_TOKEN=pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ
      - PRIVATE_KEY_PASSPHRASE=a7dsf78sadg87ad87sfagsadg78
      - "DEBUG=${DEBUG}"
      - EMAIL_SUPPORT=support@human-connection.org
      - EMAIL_DEFAULT_SENDER=info@human-connection.org
      - PUBLIC_REGISTRATION=true
    command: yarn run dev
  neo4j:
    image: schoolsinmotion/neo4j:latest
    networks:
      - hc-network
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7687:7687
      - 7474:7474
networks:
  hc-network:
