version: "3.4"

services:
  ########################################################
  # WEBAPP ###############################################
  ########################################################
  webapp:
    platform: linux/amd64

  ########################################################
  # BACKEND ##############################################
  ########################################################
  backend:
    platform: linux/amd64

  ########################################################
  # NEO4J ################################################
  ########################################################
  neo4j:
    platform: linux/amd64

  ########################################################
  # MAINTENANCE ##########################################
  ########################################################
  maintenance:
    platform: linux/amd64

  ########################################################
  # MAILSERVER TO FAKE SMTP ##############################
  ########################################################
  mailserver:
    platform: linux/amd64
