version: "3.4"

services:
  webapp:
    build:
      context: webapp
    environment:
      - PUBLIC_REGISTRATION=true
  backend:
    build:
      context: backend
    environment:
      - SMTP_HOST=mailserver
      - SMTP_PORT=25
      - SMTP_IGNORE_TLS=true
      - PUBLIC_REGISTRATION=true
  mailserver:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    networks:
      - hc-network

networks:
  hc-network:
