kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-persistent
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true