kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-persistent
  labels:
    app.kubernetes.io/name:	"{{ .Chart.Name }}"
    app.kubernetes.io/instance:	"{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/version: "{{ .Chart.appVersion }}"
    app.kubernetes.io/component: "storage-persistent"
    app.kubernetes.io/part-of:	"{{ .Chart.Name }}"
provisioner: {{ .Values.STORAGE.PROVISIONER }}
reclaimPolicy: {{ .Values.STORAGE.RECLAIM_POLICY }}
volumeBindingMode: {{ .Values.STORAGE.VOLUME_BINDING_MODE }}
allowVolumeExpansion: {{ .Values.STORAGE.ALLOW_VOLUME_EXPANSION }}