name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build neo4j base image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/neo4j
          tags: bare
          path: Human-Connection/neo4j/
          push: false
      - name: Build backend base image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/nitro-backend
          tags: bare
          path: Human-Connection/backend/
          push: false
      - name: Build webapp base image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/nitro-web
          tags: bare
          path: Human-Connection/webapp/
          push: false

      - name: Build neo4j customized image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/neo4j
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          path: neo4j/
          push: true
      - name: Build backend customized image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          path: backend/
          push: true
      - name: Build webapp customized image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/webapp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          path: webapp/
          push: true
