name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Rebrand
        run: cp -r webapp/* fyphe_O/webapp/
      - name: Build neo4j
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/neo4j
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          path: fyphe_O/neo4j/
      - name: Build backend
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          path: fyphe_O/backend/
      - name: Build webapp
        uses: docker/build-push-action@v1.1.0
        with:
          repository: schoolsinmotion/webapp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          path: fyphe_O/webapp/
