name: CI

on: [push]

jobs:
  build:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Check translation files
        run: |
          Human-Connection/scripts/translations/sort.sh
          Human-Connection/scripts/translations/missing-keys.sh
