name: ocelot.social cache cleanup on pr closing


on:
  pull_request:
    types:
      - closed

jobs:
  clean-branch-cache:
    name: Clean branch cache
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache list --branch TODO:this_current_branch --order desc --sort created-at
 #         gh actions-cache delete -R Ocelot-Social-Community/Ocelot-Social --confirm
