name: ocelot.social end-to-end test CI
on: push

jobs:
  fullstack_tests:
    name: Fullstack tests
    runs-on: ubuntu-latest
    # env:
    #   jobs: 8
    # strategy:
    #   matrix:
    #     # run copies of the current job in parallel
    #     job: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: webapp | copy env file
      #   run: cp webapp/.env.template webapp/.env

      # - name: backend | copy env file
      #   run: cp backend/.env.template backend/.env

      # - name: boot up test system | docker-compose
      #   run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --detach --no-deps webapp neo4j backend

      - name: Full stack tests | prepare
        run: |
          wget --no-verbose -O /opt/cucumber-json-formatter "https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-386"
          chmod +x /opt/cucumber-json-formatter
          sudo ln -fs /opt/cucumber-json-formatter /usr/bin/cucumber-json-formatter
          cd backend
          yarn install
          yarn build
          cd ..
          yarn install

      - name: Full stack tests | run tests
        id: e2e-tests
        run: yarn run cypress:run --spec cypress/e2e/Internationalization.feature,cypress/e2e/Post.Comment.feature

      ##########################################################################
      # UPLOAD SCREENSHOTS - IF TESTS FAIL #####################################
      ##########################################################################
      - name: Full stack tests | if tests failed, compile html report
        if: ${{ failure() && steps.e2e-tests.conclusion == 'failure' }}
        run: |
          cd cypress/
          node create-cucumber-html-report.js
  
      - name: End-to-end tests | if tests failed, upload report
        id: e2e-report
        if: ${{ failure() && steps.e2e-tests.conclusion == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report-pr${{ steps.pr.outputs.number }}
          path: /home/runner/work/gradido/gradido/e2e-tests/cypress/reports/cucumber_html_report

